[keyboards]
  [keyboards.SE07T0]
    Name = "Realforce 87U Tenkeyless (White/Gray)"
    Price = "199.00"
    Model = "SE07T0"
    Image = "/proddata/images/th/SE070S_full1000_th180x180.jpg"
    Available = true
  [keyboards.SE08T0]
    Name = "Realforce 87U Tenkeyless 55g (White/Gray)"
    Price = "205.00"
    Model = "SE08T0"
    Image = "/proddata/images/th/SE070S_full1000_th180x180.jpg"
    Available = false
  [keyboards.SE17T0]
    Name = "Realforce 87U Tenkeyless (Black)"
    Price = "199.00"
    Model = "SE17T0"
    Image = "/proddata/images/th/87UB_full1000_th180x180.jpg"
    Available = true
  [keyboards.SE18T0]
    Name = "Realforce 87U Tenkeyless 55g (Black)"
    Price = "205.00"
    Model = "SE18T0"
    Image = "/proddata/images/th/87UB_full1000_th180x180.jpg"
    Available = false
  [keyboards.SE19E0]
    Name = "Realforce 87U All-45g \"EK Edition\" (Black/Dark Gray)"
    Price = "220.00"
    Model = "SE19E0"
    Image = "/proddata/images/th/se19e0_1000_117_th180x180.jpg"
    Available = false
